### ISSUE TITLE
Redesign landing page

### ISSUE THREAD

**Issue by cmeessen** [hifis-net/RSD-as-a-service#2]
Adjust landing page to be shown in Helmholtz corporate design.

The page should be completely reworked and contain placeholders for the following content

* [x] What is the Research Software Directory and what is it for?
* [x] Short teaser for the latest Software Spotlight
* [ ] How to participate
* [x] Participating Centres
* [x] Partner Organisations

Other mandatory content

* [x] Link to imprint
* [x] Link to data protection declaration

**Comment by cmeessen** [comment]
The font Helmholtz Halvar font will be integrated via a git submodule from a private repository.

**Comment by dubst3pp4** [comment]
TODO:
- [x] include fonts
- [ ] define colors
