### ISSUE TITLE
Project status bar colors

### ISSUE THREAD

**Issue by cmeessen** [hifis-net/RSD-as-a-service#27]
Mentioned in #24 by @heluna:

> The "Status bar"  on top of the Start/End date is kind of hidden because of same background color. In Starting mode you can see no bar at all, in "running" you just see the blue part.

**Comment by ruester** [comment]
Which status bar is meant? Could you add a screenshot or explain the steps I need to see this status bar?

**Comment by cmeessen** [comment]
![image](https://user-images.githubusercontent.com/14222414/187370660-5218d955-4887-4049-ae98-418ef5366f1a.png)

On a project's page, e.g. [here](https://helmholtz.software/projects/hifis).
