### ISSUE TITLE
Helmholtz Scrollbar not shown on iOS Safari and Linux Firefox

### ISSUE THREAD

**Issue by cmeessen** [hifis-net/RSD-as-a-service#40]
The Helmholtz Scrollbar in green is not visible on:

* iOS Safari (iOS 15.5)
* Firefox (Linux, v103.0)

**Comment by cmeessen** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by ruester** [comment]
it may be possible to use https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color instead

**Comment by cmeessen** [comment]
The browser compatibility list doesn't look very promising for it to be a universal solution:

![image](https://user-images.githubusercontent.com/14222414/187370979-891b13d5-ed8d-470f-8473-6040d51ecc20.png)

**Comment by ruester** [comment]
> The browser compatibility list doesn't look very promising for it to be a universal solution

No, but combining the individual CSS rules does the trick :wink:
