### ISSUE TITLE
Update to RSD v1.2.2

### ISSUE THREAD

**Issue by cmeessen** [hifis-net/RSD-as-a-service#42]
As of 2022-08-04, there is a new version [v1.2.2](https://github.com/research-software-directory/RSD-as-a-service/releases/tag/v1.2.2)

It contains two bugfixes

* make DOI's case insensitive in the mentions scraper (645ed2f)
* use case insensitive column type for DOI's (b1d9a1e)

The update performs changes to the database. There is a migration script from v1.2.1 (current) to 1.2.2 here:

https://github.com/research-software-directory/RSD-production/blob/main/database-migration/migration-scripts/1.2.1-to-1.2.2.sql

The migration script needs to be inspected manually first. We also need to check whether we have duplicate DOIs in the database (although it is unlikely at the moment).

**Comment by ruester** [comment]
I've checked it in our staging and production DB and we had no duplicates :+1: 
I deployed a new rebased version to staging and production and then ran the DB migration steps from the script, so we are up to date now with upstream.
