### ISSUE TITLE
Header text is printed bold on Chrome (Windows)

### ISSUE THREAD

**Issue by cmeessen** [hifis-net/RSD-as-a-service#49]
Here is a screenshot in Chromium (104.0.5112.79) on Linux

![image](https://user-images.githubusercontent.com/14222414/189841666-4a5e9bb3-4f7f-4526-a742-287a8c765545.png)

and one from Chrome 105.0.5195.102 on Windows 10

![image](https://user-images.githubusercontent.com/14222414/189841723-377f02a0-b2da-422c-b787-267b4f9d5615.png)

Apart from the "Research Software Directory", every other text is printed bold in Windows. However, this should not be the case.

**Comment by ruester** [comment]
@cmeessen did you test with the same resolution for each Chrome? Do other websites (for example Google or Amazon) look different too?

**Comment by cmeessen** [comment]
Same resolution, yes some nonrelated pages look different too. I just did some quick tests and this appears to be related to rendering bright text on dark background. Happens both in Firefox and Chrome.

**Comment by ruester** [comment]
I also tested now on a virtual machine with Windows and I can see some differences (mostly due to the different resolution), but not in the CSS (same font-weight/size on both Chrome instances).

**Comment by cmeessen** [comment]
Yes, this behaviour seems to be related to the anti-aliasing and has been exiting since quite some time. Here is a post on [stackoverflow](https://stackoverflow.com/questions/14477265/css-white-text-on-black-background-looks-bolder). However, the suggested fixes did not work for me.

**Comment by cmeessen** [comment]
This problem was solved with changing the font #51
