### ISSUE TITLE
Search function should include keywords and main text

### ISSUE THREAD

**Issue by neelju** [hifis-net/RSD-as-a-service#69]
I am using the search like this:
![grafik](https://user-images.githubusercontent.com/116571209/197539599-d8cbabb9-dbef-4723-9c15-5f624d2a1b6a.png)

I expect to find:
![grafik](https://user-images.githubusercontent.com/116571209/197539779-6c504c14-f7f4-49cf-a21d-91ca49631894.png)

Note the keyword: Remote sensing

Please support also case insensitive search.

**Comment by cmeessen** [comment]
Thank you for the feedback. Keywords can be filtered by after clicking on the "Filter" icon next to the search field:

![image](https://user-images.githubusercontent.com/14222414/198245589-1593aec0-01eb-4b57-86ff-a3e29897b45c.png)

**Comment by cmeessen** [comment]
Including keyword search in the Software search bar will be included with https://github.com/research-software-directory/RSD-as-a-service/pull/625

**Comment by cmeessen** [comment]
Feature was implemented with #79
